function showHome() {
    document.getElementById('home-container').style.display = 'block';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('home-bg');
}

function showProfil() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'block';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';

    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('profil-bg');
}

function showPayment() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'block';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('payment-bg');
}

function showEditProfil() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'block';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('editprofil-bg');
}

function showLeaderboard() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'block';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('leaderboard-bg');
}

function showBelanja() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'block';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('belanja-bg');
}

function showLabirin() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'block';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('labirin-bg');
}

function showLogin() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'block';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('login-bg');
}

function showSignup() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'block';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('signup-bg');
}

function showSaya() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'block';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('saya-bg');
}

function showRoll() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'block';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('roll-bg');
}

function showBurung() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'block';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('burung-bg');
}

function showPasar() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'block';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('pasar-bg');
}

function showDisclaimer() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'block';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('disclaimer-bg');
}

function showFaq() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'block';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('faq-bg');
}

function showReturnPolicy() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'block';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('returnpolicy-bg');
}

function showPrivacyPolicy() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'block';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('privacypolicy-bg');
}

function showZona1() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'block';
    document.getElementById('cross-container').style.display = 'none';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('cross-bg');
    document.getElementById('gameBody').classList.add('zona1-bg');
}

function showCross() {
    document.getElementById('home-container').style.display = 'none';
    document.getElementById('profil-container').style.display = 'none';
    document.getElementById('payment-container').style.display = 'none';
    document.getElementById('editprofil-container').style.display = 'none';
    document.getElementById('leaderboard-container').style.display = 'none';
    document.getElementById('belanja-container').style.display = 'none';
    document.getElementById('labirin-container').style.display = 'none';
    document.getElementById('login-container').style.display = 'none';
    document.getElementById('signup-container').style.display = 'none';
    document.getElementById('saya-container').style.display = 'none';
    document.getElementById('roll-container').style.display = 'none';
    document.getElementById('burung-container').style.display = 'none';
    document.getElementById('pasar-container').style.display = 'none';
    document.getElementById('disclaimer-container').style.display = 'none';
    document.getElementById('faq-container').style.display = 'none';
    document.getElementById('returnpolicy-container').style.display = 'none';
    document.getElementById('privacypolicy-container').style.display = 'none';
    document.getElementById('zona1-container').style.display = 'none';
    document.getElementById('cross-container').style.display = 'block';
    
    document.getElementById('gameBody').classList.remove('home-bg');
    document.getElementById('gameBody').classList.remove('profil-bg');
    document.getElementById('gameBody').classList.remove('payment-bg');
    document.getElementById('gameBody').classList.remove('editprofil-bg');
    document.getElementById('gameBody').classList.remove('leaderboard-bg');
    document.getElementById('gameBody').classList.remove('belanja-bg');
    document.getElementById('gameBody').classList.remove('labirin-bg');
    document.getElementById('gameBody').classList.remove('login-bg');
    document.getElementById('gameBody').classList.remove('signup-bg');
    document.getElementById('gameBody').classList.remove('saya-bg');
    document.getElementById('gameBody').classList.remove('roll-bg');
    document.getElementById('gameBody').classList.remove('burung-bg');
    document.getElementById('gameBody').classList.remove('pasar-bg');
    document.getElementById('gameBody').classList.remove('disclaimer-bg');
    document.getElementById('gameBody').classList.remove('faq-bg');
    document.getElementById('gameBody').classList.remove('returnpolicy-bg');
    document.getElementById('gameBody').classList.remove('privacypolicy-bg');
    document.getElementById('gameBody').classList.remove('zona1-bg');
    document.getElementById('gameBody').classList.add('cross-bg');
}
